version: "3.9"

services:
  phoenix-db:
    image: postgres:17.7
    container_name: phoenix-db
    environment:
      POSTGRES_USER: ${PHX_DB_USER}
      POSTGRES_PASSWORD: ${PHX_DB_PASSWORD}
      POSTGRES_DB: ${PHX_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - phoenix_db_data:/var/lib/postgresql/data

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD}
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: ${LDAP_READONLY_USER_USERNAME}
      LDAP_READONLY_USER_PASSWORD: ${LDAP_READONLY_USER_PASSWORD}
    ports:
      - "389:389"
    volumes:
      - openldap_data:/var/lib/ldap
      - openldap_config:/etc/ldap/slapd.d
      - ./openldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom:ro

  keycloak-db:
    image: postgres:17.7
    container_name: keycloak-db
    environment:
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
      POSTGRES_DB: ${KC_DB_NAME}
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.5
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: ${KC_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
      - openldap
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro

volumes:
  phoenix_db_data:
  openldap_data:
  openldap_config:
  keycloak_db_data:
